site_name: Open Reader's Bibles
nav:
  - Home: index.md
  - Reader's Bibles:
     - Good glosses: good-glosses.md
     - Deciding on frequency thresholds: frequency-thresholds.md
     - Reader’s Bibles and Interlinear Bibles: readersbibles.md
     - Glossary of Terms: glossary.md
  - User's Guide:
    - The Workspace: workspace.md
    - Glosses & Votes: glosses-votes.md
    - Adding Glosses: gloss-types.md
    - Markdown: markdown.md
  - Project Settings:
    - General Settings: project-settings/general-settings.md
    - Canons: project-settings/canons.md
    - Parsing Formats: project-settings/parsing-formats.md
    - Publication Configurations: project-settings/publication-configurations.md
    - Project Members: project-settings/project-members.md
  - Publication:
    - Preparing to Publish: preparing-to-publish.md
    - Publishing: publication-overview.md
    - Fonts: fonts.md
  - Advanced:
    - Power Users: project-settings/power-users.md
    - Do-It-Yourself Publication: DIY.md
  - About:
    - About the project: about.md
    - License: license.md
    - Credits: credits.md
    - Security: security.md
theme: readthedocs