site_name: Open Reader's Bibles
nav:
  - Home: index.md
  - Reader's Bibles:
     - Good glosses: good-glosses.md
     - Deciding on frequency thresholds: frequency-thresholds.md
     - Reader’s Bibles and Interlinear Bibles: readersbibles.md
     - Glossary of Terms: glossary.md
  - User's Guide:
    - The Workspace: workspace.md
    - Glosses & Votes: glosses-votes.md
    - Adding Glosses: gloss-types.md
    - Project Settings: project-settings.md
    - Markdown: markdown.md
    - Publication Overview: publication-overview.md
  - Publication:
    - Fonts: fonts.md
    - Do It Yourself: DIY.md
  - About:
    - About the project: about.md
    - License: license.md
    - Credits: credits.md
    - Security: security.md
theme: readthedocs